name: run-ci-tests

on:
  pull_request:
    branches:
    - main
    - release-*

jobs:
  runtests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: setup-go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: tidy
      run: make tidy

    - name: vet
      run: make vet

    - name: format
      run: make fmt

    - name: test
      run: make cover

    - name: convert-cov-output
      uses: jandelgado/gcov2lcov-action@v1.0.9
    
    - name: coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.lcov
